export const AFFILIATE_LIST_REQUEST = 'AFFILIATE_LIST_REQUEST';
export const AFFILIATE_LIST_SUCCESS = 'AFFILIATE_LIST_SUCCESS';
export const AFFILIATE_LIST_FAIL = 'AFFILIATE_LIST_FAIL';

export const AFFILIATE_DETAILS_REQUEST = 'AFFILIATE_DETAILS_REQUEST';
export const AFFILIATE_DETAILS_SUCCESS = 'AFFILIATE_DETAILS_SUCCESS';
export const AFFILIATE_DETAILS_FAIL = 'AFFILIATE_DETAILS_FAIL';

export const AFFILIATE_SAVE_REQUEST = 'AFFILIATE_SAVE_REQUEST';
export const AFFILIATE_SAVE_SUCCESS = 'AFFILIATE_SAVE_SUCCESS';
export const AFFILIATE_SAVE_FAIL = 'AFFILIATE_SAVE_FAIL';
export const AFFILIATE_REMOVE_STATE = 'AFFILIATE_REMOVE_STATE';

export const AFFILIATE_DELETE_REQUEST = 'AFFILIATE_DELETE_REQUEST';
export const AFFILIATE_DELETE_SUCCESS = 'AFFILIATE_DELETE_SUCCESS';
export const AFFILIATE_DELETE_FAIL = 'AFFILIATE_DELETE_FAIL';
