export const CHIP_LIST_REQUEST = 'CHIP_LIST_REQUEST';
export const CHIP_LIST_SUCCESS = 'CHIP_LIST_SUCCESS';
export const CHIP_LIST_FAIL = 'CHIP_LIST_FAIL';

export const CHIP_DETAILS_REQUEST = 'CHIP_DETAILS_REQUEST';
export const CHIP_DETAILS_SUCCESS = 'CHIP_DETAILS_SUCCESS';
export const CHIP_DETAILS_FAIL = 'CHIP_DETAILS_FAIL';

export const CHIP_SAVE_REQUEST = 'CHIP_SAVE_REQUEST';
export const CHIP_SAVE_SUCCESS = 'CHIP_SAVE_SUCCESS';
export const CHIP_SAVE_FAIL = 'CHIP_SAVE_FAIL';

export const CHIP_DELETE_REQUEST = 'CHIP_DELETE_REQUEST';
export const CHIP_DELETE_SUCCESS = 'CHIP_DELETE_SUCCESS';
export const CHIP_DELETE_FAIL = 'CHIP_DELETE_FAIL';
