export const CONTENT_LIST_REQUEST = 'CONTENT_LIST_REQUEST';
export const CONTENT_LIST_SUCCESS = 'CONTENT_LIST_SUCCESS';
export const CONTENT_LIST_FAIL = 'CONTENT_LIST_FAIL';

export const CONTENT_DETAILS_REQUEST = 'CONTENT_DETAILS_REQUEST';
export const CONTENT_DETAILS_SUCCESS = 'CONTENT_DETAILS_SUCCESS';
export const CONTENT_DETAILS_FAIL = 'CONTENT_DETAILS_FAIL';

export const CONTENT_SAVE_REQUEST = 'CONTENT_SAVE_REQUEST';
export const CONTENT_SAVE_SUCCESS = 'CONTENT_SAVE_SUCCESS';
export const CONTENT_SAVE_FAIL = 'CONTENT_SAVE_FAIL';

export const CONTENT_DELETE_REQUEST = 'CONTENT_DELETE_REQUEST';
export const CONTENT_DELETE_SUCCESS = 'CONTENT_DELETE_SUCCESS';
export const CONTENT_DELETE_FAIL = 'CONTENT_DELETE_FAIL';
