export const EMAIL_LIST_REQUEST = 'EMAIL_LIST_REQUEST';
export const EMAIL_LIST_SUCCESS = 'EMAIL_LIST_SUCCESS';
export const EMAIL_LIST_FAIL = 'EMAIL_LIST_FAIL';

export const EMAIL_DETAILS_REQUEST = 'EMAIL_DETAILS_REQUEST';
export const EMAIL_DETAILS_SUCCESS = 'EMAIL_DETAILS_SUCCESS';
export const EMAIL_DETAILS_FAIL = 'EMAIL_DETAILS_FAIL';

export const EMAIL_SAVE_REQUEST = 'EMAIL_SAVE_REQUEST';
export const EMAIL_SAVE_SUCCESS = 'EMAIL_SAVE_SUCCESS';
export const EMAIL_SAVE_FAIL = 'EMAIL_SAVE_FAIL';

export const EMAIL_DELETE_REQUEST = 'EMAIL_DELETE_REQUEST';
export const EMAIL_DELETE_SUCCESS = 'EMAIL_DELETE_SUCCESS';
export const EMAIL_DELETE_FAIL = 'EMAIL_DELETE_FAIL';
