export const EXPENSE_LIST_REQUEST = 'EXPENSE_LIST_REQUEST';
export const EXPENSE_LIST_SUCCESS = 'EXPENSE_LIST_SUCCESS';
export const EXPENSE_LIST_FAIL = 'EXPENSE_LIST_FAIL';

export const EXPENSE_DETAILS_REQUEST = 'EXPENSE_DETAILS_REQUEST';
export const EXPENSE_DETAILS_SUCCESS = 'EXPENSE_DETAILS_SUCCESS';
export const EXPENSE_DETAILS_FAIL = 'EXPENSE_DETAILS_FAIL';

export const EXPENSE_SAVE_REQUEST = 'EXPENSE_SAVE_REQUEST';
export const EXPENSE_SAVE_SUCCESS = 'EXPENSE_SAVE_SUCCESS';
export const EXPENSE_SAVE_FAIL = 'EXPENSE_SAVE_FAIL';

export const EXPENSE_DELETE_REQUEST = 'EXPENSE_DELETE_REQUEST';
export const EXPENSE_DELETE_SUCCESS = 'EXPENSE_DELETE_SUCCESS';
export const EXPENSE_DELETE_FAIL = 'EXPENSE_DELETE_FAIL';
