export const FEATURE_LIST_REQUEST = 'FEATURE_LIST_REQUEST';
export const FEATURE_LIST_SUCCESS = 'FEATURE_LIST_SUCCESS';
export const FEATURE_LIST_FAIL = 'FEATURE_LIST_FAIL';

export const FEATURE_DETAILS_REQUEST = 'FEATURE_DETAILS_REQUEST';
export const FEATURE_DETAILS_SUCCESS = 'FEATURE_DETAILS_SUCCESS';
export const FEATURE_DETAILS_FAIL = 'FEATURE_DETAILS_FAIL';

export const FEATURE_SAVE_REQUEST = 'FEATURE_SAVE_REQUEST';
export const FEATURE_SAVE_SUCCESS = 'FEATURE_SAVE_SUCCESS';
export const FEATURE_SAVE_FAIL = 'FEATURE_SAVE_FAIL';

export const FEATURE_DELETE_REQUEST = 'FEATURE_DELETE_REQUEST';
export const FEATURE_DELETE_SUCCESS = 'FEATURE_DELETE_SUCCESS';
export const FEATURE_DELETE_FAIL = 'FEATURE_DELETE_FAIL';
