export const PALETTE_LIST_REQUEST = 'PALETTE_LIST_REQUEST';
export const PALETTE_LIST_SUCCESS = 'PALETTE_LIST_SUCCESS';
export const PALETTE_LIST_FAIL = 'PALETTE_LIST_FAIL';

export const MY_PALETTE_LIST_REQUEST = 'MY_PALETTE_LIST_REQUEST';
export const MY_PALETTE_LIST_SUCCESS = 'MY_PALETTE_LIST_SUCCESS';
export const MY_PALETTE_LIST_FAIL = 'MY_PALETTE_LIST_FAIL';

export const PALETTE_DETAILS_REQUEST = 'PALETTE_DETAILS_REQUEST';
export const PALETTE_DETAILS_SUCCESS = 'PALETTE_DETAILS_SUCCESS';
export const PALETTE_DETAILS_FAIL = 'PALETTE_DETAILS_FAIL';

export const PALETTE_SAVE_REQUEST = 'PALETTE_SAVE_REQUEST';
export const PALETTE_SAVE_SUCCESS = 'PALETTE_SAVE_SUCCESS';
export const PALETTE_SAVE_FAIL = 'PALETTE_SAVE_FAIL';

export const PALETTE_DELETE_REQUEST = 'PALETTE_DELETE_REQUEST';
export const PALETTE_DELETE_SUCCESS = 'PALETTE_DELETE_SUCCESS';
export const PALETTE_DELETE_FAIL = 'PALETTE_DELETE_FAIL';
