export const PARCEL_LIST_REQUEST = 'PARCEL_LIST_REQUEST';
export const PARCEL_LIST_SUCCESS = 'PARCEL_LIST_SUCCESS';
export const PARCEL_LIST_FAIL = 'PARCEL_LIST_FAIL';

export const MY_PARCEL_LIST_REQUEST = 'MY_PARCEL_LIST_REQUEST';
export const MY_PARCEL_LIST_SUCCESS = 'MY_PARCEL_LIST_SUCCESS';
export const MY_PARCEL_LIST_FAIL = 'MY_PARCEL_LIST_FAIL';

export const PARCEL_DETAILS_REQUEST = 'PARCEL_DETAILS_REQUEST';
export const PARCEL_DETAILS_SUCCESS = 'PARCEL_DETAILS_SUCCESS';
export const PARCEL_DETAILS_FAIL = 'PARCEL_DETAILS_FAIL';

export const PARCEL_SAVE_REQUEST = 'PARCEL_SAVE_REQUEST';
export const PARCEL_SAVE_SUCCESS = 'PARCEL_SAVE_SUCCESS';
export const PARCEL_SAVE_FAIL = 'PARCEL_SAVE_FAIL';

export const PARCEL_DELETE_REQUEST = 'PARCEL_DELETE_REQUEST';
export const PARCEL_DELETE_SUCCESS = 'PARCEL_DELETE_SUCCESS';
export const PARCEL_DELETE_FAIL = 'PARCEL_DELETE_FAIL';
