export const PAYCHECK_LIST_REQUEST = 'PAYCHECK_LIST_REQUEST';
export const PAYCHECK_LIST_SUCCESS = 'PAYCHECK_LIST_SUCCESS';
export const PAYCHECK_LIST_FAIL = 'PAYCHECK_LIST_FAIL';

export const MY_PAYCHECK_LIST_REQUEST = 'MY_PAYCHECK_LIST_REQUEST';
export const MY_PAYCHECK_LIST_SUCCESS = 'MY_PAYCHECK_LIST_SUCCESS';
export const MY_PAYCHECK_LIST_FAIL = 'MY_PAYCHECK_LIST_FAIL';

export const PAYCHECK_DETAILS_REQUEST = 'PAYCHECK_DETAILS_REQUEST';
export const PAYCHECK_DETAILS_SUCCESS = 'PAYCHECK_DETAILS_SUCCESS';
export const PAYCHECK_DETAILS_FAIL = 'PAYCHECK_DETAILS_FAIL';

export const PAYCHECK_SAVE_REQUEST = 'PAYCHECK_SAVE_REQUEST';
export const PAYCHECK_SAVE_SUCCESS = 'PAYCHECK_SAVE_SUCCESS';
export const PAYCHECK_SAVE_FAIL = 'PAYCHECK_SAVE_FAIL';

export const PAYCHECK_DELETE_REQUEST = 'PAYCHECK_DELETE_REQUEST';
export const PAYCHECK_DELETE_SUCCESS = 'PAYCHECK_DELETE_SUCCESS';
export const PAYCHECK_DELETE_FAIL = 'PAYCHECK_DELETE_FAIL';
