export const PROMO_LIST_REQUEST = 'PROMO_LIST_REQUEST';
export const PROMO_LIST_SUCCESS = 'PROMO_LIST_SUCCESS';
export const PROMO_LIST_FAIL = 'PROMO_LIST_FAIL';

export const PROMO_DETAILS_REQUEST = 'PROMO_DETAILS_REQUEST';
export const PROMO_DETAILS_SUCCESS = 'PROMO_DETAILS_SUCCESS';
export const PROMO_DETAILS_FAIL = 'PROMO_DETAILS_FAIL';

export const PROMO_SAVE_REQUEST = 'PROMO_SAVE_REQUEST';
export const PROMO_SAVE_SUCCESS = 'PROMO_SAVE_SUCCESS';
export const PROMO_SAVE_FAIL = 'PROMO_SAVE_FAIL';

export const PROMO_DELETE_REQUEST = 'PROMO_DELETE_REQUEST';
export const PROMO_DELETE_SUCCESS = 'PROMO_DELETE_SUCCESS';
export const PROMO_DELETE_FAIL = 'PROMO_DELETE_FAIL';
