export const SETTING_LIST_REQUEST = 'SETTING_LIST_REQUEST';
export const SETTING_LIST_SUCCESS = 'SETTING_LIST_SUCCESS';
export const SETTING_LIST_FAIL = 'SETTING_LIST_FAIL';

export const SETTING_DETAILS_REQUEST = 'SETTING_DETAILS_REQUEST';
export const SETTING_DETAILS_SUCCESS = 'SETTING_DETAILS_SUCCESS';
export const SETTING_DETAILS_FAIL = 'SETTING_DETAILS_FAIL';

export const SETTING_SAVE_REQUEST = 'SETTING_SAVE_REQUEST';
export const SETTING_SAVE_SUCCESS = 'SETTING_SAVE_SUCCESS';
export const SETTING_SAVE_FAIL = 'SETTING_SAVE_FAIL';

export const SETTING_DELETE_REQUEST = 'SETTING_DELETE_REQUEST';
export const SETTING_DELETE_SUCCESS = 'SETTING_DELETE_SUCCESS';
export const SETTING_DELETE_FAIL = 'SETTING_DELETE_FAIL';

export const SHOW_SEARCH_BAR = 'SHOW_SEARCH_BAR';
export const HIDE_SEARCH_BAR = 'HIDE_SEARCH_BAR';
