export const SURVEY_LIST_REQUEST = 'SURVEY_LIST_REQUEST';
export const SURVEY_LIST_SUCCESS = 'SURVEY_LIST_SUCCESS';
export const SURVEY_LIST_FAIL = 'SURVEY_LIST_FAIL';

export const SURVEY_DETAILS_REQUEST = 'SURVEY_DETAILS_REQUEST';
export const SURVEY_DETAILS_SUCCESS = 'SURVEY_DETAILS_SUCCESS';
export const SURVEY_DETAILS_FAIL = 'SURVEY_DETAILS_FAIL';

export const SURVEY_SAVE_REQUEST = 'SURVEY_SAVE_REQUEST';
export const SURVEY_SAVE_SUCCESS = 'SURVEY_SAVE_SUCCESS';
export const SURVEY_SAVE_FAIL = 'SURVEY_SAVE_FAIL';
export const SURVEY_REMOVE_STATE = 'SURVEY_REMOVE_STATE';

export const SURVEY_DELETE_REQUEST = 'SURVEY_DELETE_REQUEST';
export const SURVEY_DELETE_SUCCESS = 'SURVEY_DELETE_SUCCESS';
export const SURVEY_DELETE_FAIL = 'SURVEY_DELETE_FAIL';
